img_ocean/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from . import settings


from .views import HomePageView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^p/', include('posts.urls', namespace='posts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from __future__ import absolute_import
from django.conf.urls import url
from . import views


urlpatterns = [
    url(
        r'create/$',
        views.CreatePostView.as_view(),
        name='create'
    ),
    url(
        r'(?P<slug>[\w\-]{10})/$',
        views.DetailPostView.as_view(),
        name='view'
    ),
]

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
import string as str
from random import choice


def generate_id():
    n = 10
    random = str.ascii_uppercase + str.ascii_lowercase + str.digits
    return ''.join(choice(random) for _ in range(n))


class Post(models.Model):
    photo = models.ImageField(upload_to='post_photos')
    slug = models.SlugField(unique=True, max_length=10, default=generate_id)
    caption = models.CharField(max_length=50, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Posts'
        ordering = ['-date_created', ]

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse('posts:view', kwargs={'slug': self.slug})

posts/forms.py
from __future__ import absolute_import

from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit

from posts.models import Post


class CreatePostForm(forms.ModelForm):
    class Meta:
        fields = ('photo', 'caption', )
        model = Post

    def __init__(self, *args, **kwargs):
        super(CreatePostForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'photo',
            'caption',
            Submit('post', 'Post', css_class='btn btn-primary')
        )

img_ocean/views.py
from django.views import generic
from posts.models import Post
from posts.helpers import get_posts


class HomePageView(generic.ListView):
    model = Post
    template_name = 'home.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return get_posts()

posts/views.py
from __future__ import absolute_import

from django.views import generic

from .models import Post
from .forms import CreatePostForm
from .helpers import get_post


class DetailPostView(generic.DetailView):
    model = Post
    template_name = 'posts/post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super(DetailPostView, self).get_context_data(**kwargs)
        context['post'] = get_post(self.kwargs['slug'])

        return context


class CreatePostView(generic.CreateView):
    model = Post
    form_class = CreatePostForm
    template_name = 'posts/post_form.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()

        return super(CreatePostView, self).form_valid(form)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Image Ocean{% endblock title %}</title>
    <link rel="stylesheet" href="https://bootswatch.com/superhero/bootstrap.min.css">
    <style>
        body {
            padding-bottom: 20px;
            padding-top: 70px;
        }
        .messages {
            list-style: none;
        }
        .red, .red:hover, .red:visited,
        .red:active, .red:focus, .red:link {
            color: #d9534f;
        }

    </style>
    {% block css %}{% endblock css %}
</head>
    #body1
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Image Ocean</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'posts:create' %}">Create Post</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">

        <h1>{% block headline %}{% endblock headline %}</h1>

        {% block content %}{% endblock content %}
        {% block copy_url %}{% endblock %}
    </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block js %}{% endblock js %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8"><h1>Most recent images</h1></div>
        <div class="col-md-2"></div>
    </div>
    {% for post in posts %}
        {% include 'posts/post.html' %}
    {% endfor %}
{% endblock %}

templates/posts/post.html
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div id="{{ post.slug }}" class="panel panel-default" style="margin-top: 20px">
            <div class="panel-heading">
                <a href="{% url 'posts:view' post.slug %}">{{ post.date_created|timesince }}</a>
            </div>
            <div class="panel-body">
                <img class="img-responsive" src="{{ post.photo.url }}" alt="{{ post.caption }}" width="720px"/>
                <p class="lead" style="margin-top: 25px">{{ post.caption }}</p>
            </div>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>

templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}Image Ocean: "{{ post.caption }}"{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8"><h3>Please copy this url: <a href="http://127.0.0.1:8000/p/{{ post.slug }}/">http://127.0.0.1:8000/p/{{ post.slug }}</a>
        </h3></div>
        <div class="col-md-2"></div>
    </div>
    {% include 'posts/post.html' %}
{% endblock %}

templates/posts/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    {% crispy form %}
{% endblock %}